# workflow 의 이름
name: Run Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs: 
build:
runs-on: macos-latest  
    steps:
    - uses: actions/checkout@v3  
    - name: Build Xcode  // 실행할 작업 이름
      run: | 
        xcodebuild clean test -project GithubActionTest.xcodeproj \
        -scheme GithubActionTest \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest'
